### ISSUE TITLE
GSF needs a logo

### ISSUE THREAD

**Issue by tfield** [dolfdijkstra/gst-foundation#135]
The website would look much nicer with a logo. Wouldn't it be nice to have one?

**Comment by amai** [comment]
Did you get a chance to see this? 
![image](https://cloud.githubusercontent.com/assets/432880/19660477/d94a20c8-99e4-11e6-94aa-87e3e9c8b536.png)

(made by Eric)

**Comment by tfield** [comment]
Yes, we're working on some variations for the 12.0.1 release

**Comment by tfield** [comment]
The latest candidates

![gsf-logo-350x100](https://cloud.githubusercontent.com/assets/2083963/19661469/de0435c8-9a01-11e6-8f55-3e2e5f85c88b.png)
![gsf-logo-gst-592x100](https://cloud.githubusercontent.com/assets/2083963/19661471/de05e1b6-9a01-11e6-9910-802d20af5b8f.png)
![gsf-logo-gst-592x130](https://cloud.githubusercontent.com/assets/2083963/19661470/de03ec26-9a01-11e6-9e4c-8aa0b6b9623e.png)
![gsf-logo-wcs-stack250x100](https://cloud.githubusercontent.com/assets/2083963/19661473/de1648bc-9a01-11e6-85c6-ab93ba623334.png)
![gsf-logo-wcs608x100](https://cloud.githubusercontent.com/assets/2083963/19661472/de0c76ac-9a01-11e6-825c-41a3a1750eaa.png)

**Comment by tfield** [comment]
the 3rd one looks like a winner for fit on the home page

**Comment by ebrengle** [comment]
Let me know if you need different iterations.

**Comment by tfield** [comment]
Fixed in 12.0.1
