### ISSUE TITLE
Is this project still on? I want to try new navigation service but failing to setup :( 

### ISSUE THREAD

**Issue by fatwire-dev** [dolfdijkstra/gst-foundation#157]
- I tried setting gsf-core but many issues
- I tried setting gsf-sample but gsf-core-12.1.0.0.jar is not available
- It seems project is out of sync from last 2 years.

Is GSF not available anymore ?

**Comment by dolfdijkstra** [comment]
I am not maintaining this anymore.

**Comment by tfield** [comment]
Hi Dolf -

I’d like to take over the lead on this. I’ve forked it and can switch the site over. Let me know.

Thanks,
Tony
